spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  properties:
    hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  file:
    name: app.log
  level:
    root: warn
    ## Colocando Logs especificas.
    io:
      github:
        springboot: warn
    org:
      springframework:
        web: debug
        security: trace

# trace -> Habilita todos os levels de Root -> gera muito log, não recomendado
# debug -> Pega do debug info e warn
# info -> Pega info e warn
# warn -> Pega apenas o warn -> mais recomendado

springdoc:
  override-with-generic-response: false